### PR TITLE
Added CMake + Usign raw string to avoid the backslash escaping (+linux support)

### PR DESCRIPTION
**Pull request by jonassorgenfrei**
Hey, 

i added a CMake file so it's easier to build the plugin for multiple Nuke Versions and different os (but i jsut tried windows too). 

Additionally i found out that the _message memeber variable has the non raw string entered in the input field.
Unfortunatly this introduces the need to add escaping backslashes for backslashes \\w+.
I think from an artist (less technical point of view) it could be a bit confusing to always having to escape part's of the regex and not having it like regex101 or other websites.

### CODE REVIEW

**Comment by jonassorgenfrei** [comment]
adjusted the code a little bit so it's possible to compile on linux aswell

**Comment by Ahuge** [comment]
Hi Jonas,

Thanks for this PR, it looks good.

I'll have to check this out locally because it has been a while since I worked on this. Assuming everything compiles on my end, you've made some really nice improvments!

I'll try to dig into this within the next few days!

**Comment by Ahuge** [comment]
Hi Jonas,

Thanks for this PR, it looks good.

I'll have to check this out locally because it has been a while since I worked on this. Assuming everything compiles on my end, you've made some really nice improvements!

I'll try to dig into this within the next few days!

**Comment by Ahuge** [comment]
Hi Jonas,

This is really good! Thanks for your work.

I'll merge this in!

**Comment by jonassorgenfrei** [comment]
Hey Alex,

you're welcome.
awesome thank you very much for double checking :) .

**Comment by jonassorgenfrei** [comment]
Shall i adjust the description and example image there with the "non-escaped" regex ?

**Comment by Ahuge** [comment]
Hi Jonas,

For sure, I'd love if you updated the description and image!

**Comment by jonassorgenfrei** [comment]
Hi Alex,
cool will do it on the weekend and create a new PR then :)

**Pull request merged**
